version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - atende

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - atende

    # db mysql
     environment:
      DB_HOST: 172.20.0.4
      DB_DATABASE: DASHBOARD
      DB_USERNAME: root
      DB_PASSWORD: Ncm@647534
    networks:
      - atende

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8010:80"
        environment:
            PMA_HOST: 172.20.0.4
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: Ncm@647534
        networks:
            - atende

    # redis
    redis:
        image: redis:latest
        networks:
            - atende

networks:
    atende:
        driver: bridge
